padariau regex phone ir license number
Currus1/cuddly-sniffle-be pull request #28
Opened 2022-10-09 19:52 UTC by FasterThanC

2022-10-10 06:09 UTC, Tedas1 requested changes
nekoreaguok drivers ir users jsonų

2022-10-10 06:09 UTC, Tedas1 commented on currus/currus/Models/User.cs
> +    [RegularExpression(@"^((86|\+3706)\d{3}\d{4})$")]
kodėl ne \d{7} ?

2022-10-10 19:31 UTC, BaVilius commented
Very bad. 🗡️ 🗡️ 🗡️ `f drvc`

2022-10-10 22:50 UTC, FasterThanC commented
> Very bad. 🗡️ 🗡️ 🗡️ `f drvc`

Ты кто такой?!

2022-10-11 14:07 UTC, Tedas1 approved these changes

2022-10-11 14:25 UTC, ClydeeS approved these changes

2022-10-11 15:28 UTC, merged