Trip status
Currus1/cuddly-sniffle-be pull request #39
Opened 2022-10-25 19:41 UTC by PijusZl

+ Added trip status to Trip model
+ Added function for getting all trips by trip status from database

2022-10-26 06:43 UTC, Tedas1 requested changes

2022-10-26 06:43 UTC, Tedas1 commented on currus/currus/Controllers/TripController.cs
> +    public List<Trip> GetTrips(string tripStatus)
O nebūtų simpler, kad returnintų IEnumerable metodas?

2022-10-26 06:43 UTC, Tedas1 commented on currus/currus/Controllers/TripController.cs
> +        List<Trip>? trips = _tripDbRepository.GetAllByStatus(tripStatus).ToList();
Tada čia nereiktų naujo kintamojo ir toList 🤔

2022-10-26 08:22 UTC, Tedas1 approved these changes

2022-10-26 11:20 UTC, FasterThanC approved these changes
Perfecto

2022-10-26 11:49 UTC, Tedas1 requested changes
blogas migrationas

2022-10-27 17:38 UTC, Tedas1 approved these changes

2022-10-27 17:38 UTC, merged